- .npmignore
Shouldn't include all the external repos when publishing. Also ignoring two dot files that aren't needed outside of the repo.
I haven't actually tests this, since that requires publishing.
> Ignore tests folder when publishing to npm

- lib/_patch/mocha-plugin.js
Replaced Date.now() with (new Date).getTime() because Date.now() is not supported until IE9.
> Support IE8 in Mocha tests

- lib/_patch/jasmine-plugin.js
This takes the changes from #88, squashes them into one commit, then formats the code properly (add some spacing, use consistent indentation) and fixes something I consider a bug: It moves the `clearInterval` into the `running` check, where it makes much more sense. From the commit message:
> It makes no sense to clear the interval while Jasmine is still running,
potentially never reporting results when the suite didn't finish after
the first interval ran.
I've ran `ruby tests/test.rb` to verify it works.
> Fix jasmine patch

- bin/cli.js
- lib/config.js
- lib/local.js
- lib/server.js
- lib/utils.js
Changed to BrowserStackLocal.exe instead of the jar-file.
The tunnel process is now killed when the tests are complete.
Before when using the jar-file the tunnel processes still were alive in the background after the test were completed. Which created problem the next time you ran the tests, your worker then never received the "Acknowledge" state,
Added path fix for Windows, it now works with "/" on Windows in the "test_path" config.
Fixed the Process signals to work on Windows, before you never got to the method "cleanUpAndExit" in cli.js because of how Process.kill works on Windows. It now runs "cleanUpAndExit" before exiting the process as expected.
> Windows fixes

- bin/cli.js
This commit introduces a handler for `client.getWorkers` when it receives an error argument.
This way it won't break JS from running, but instead will just report the error and continue.
This is not the best way to fix this problem, but this will prevent false statements on CI runs, creating warnings rather than fatal errros.
There's more to be done until it's reasonable, but at least it reports more specific bugs.
And it seems that it's still timing out.
> Prevent fatal error when it gets a 403 Error

- README.md
- lib/config.js
Currently the `build` property in `browserstack.json` is not working correctly. A bug introduced [here](https://github.com/browserstack/browserstack-runner/commit/8f936a400bfc276fd5c20ed34042afb87fb3f1ad#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R52) means that the `config.build` is always set to the `Local run` string. I'm presuming it should be an `else` statement there?
I've also changed it so you can have a custom build string set in your `browserstack.json`. If there is a build string set it won't set to it the 'Commit-` or 'Local run,' string but will use that instead
I've also updated the README with information about updating the `build` string.
> Allow to add custom build string

- README.md
- lib/local.js
Revert "On linux, EACCES open ... BrowserStackLocal error. Fixes #91"
This reverts commit c27a2adb88c02c72842dadb2b6fe4cce17137e28
Documents how to avoid the issue described in #91 by configuring npm
properly.
Ref #91
Fixes #105
> Local: Revert writing tunnel file into working dir, document npm fix

- bin/cli.js
- lib/server.js
* Attempts to set the URL one additional time just in case a newly created (or reused) worker fails to set it
* Similar in approach to the other PR on this issue
* Incorporates changes requested and minor code cleanup
Run with `--verbose` to see ack check and re-request behaviour.
> Retry opening URL if worker-browser fails to send request within ackTimeout

- lib/server.js
I'm testing using [tape](https://github.com/substack/tape), and am calling `BrowserStack.post` myself.
I am not supplying in any string for the `test_framework` property in browserstack.json.
When the qunit patch is included, errors occur in the console log.
This patch fixes the error, so that qunit code is only injected if the users actually ask for it.
> Don't assume qunit is the default test framework

- .jshintrc
- bin/cli.js
- lib/proxy.js
- lib/utils.js
- tests/unit/utils_spec.js
Handles `Bad or unnecessary escaping` jshint error and a few other lint errors.
Closes #99.
> jshint Fixes

- bin/cli.js
Fixes some bad misses that make the earlier fix useless, as kindly pointed by @sanox.
Thanks, @sanox.
Closes #131.
> Retry URL Fixes

- lib/local.js
In environments like Travis, the `-localIdentifier` option [is set](https://github.com/browserstack/browserstack-runner/blob/2e3f4a3c42f909cf3b957cd5bdfa5567a7e5f0a8/lib/config.js#L76) for the `BrowserStackLocal` binary used for creating the local tunnel. 
For some inexplicable reason, child_process.execFile seems to require each args array element to be an independent fragment of the command - for e.g. [ '-localIdentifier ' + 'ID:1' ] vs. [ '-localIdentifier', 'ID:1' ]. I have no idea why it works that way.
[Working Travis Build with the fix](https://travis-ci.org/shirish87/browserstack-runner-travis-test/builds).
Thanks, @TehShrike and @ausi for helping out.
Fixes #102.
> Fix for failing Travis builds

- lib/server.js
Some android browsers send a request with a '\' character prefixed to every '&',
which causes the uuid to end with a '\'.
> Temperary Fix: Sanitize worker uuid

- lib/_patch/mocha-plugin.js
Fixes issue with mocha tests printing `Tracebacks: {}` on the console instead of error stack.
Also captures errors that are reported for "multiple done" calls by waiting an extra second.
> Update mocha patch to print errors

- lib/local.js
Performs a simple check with '-version' switch, and on failure causes the binary to be downloaded again.
Fixes #143
> Verify downloaded binary before attempting to start tunnel

- bin/cli.js
- lib/logger.js
- lib/server.js
Two changes:
* `LOG_LEVEL=trace browserstack-runner --verbose` prints low level information on API request/response and code execution steps
* Worker lookup failure (as reported in #145) does not blow up the run
> Finer logging + handle worker lookup failure

- lib/server.js
API returns an error `worker is running for 15.206354 secs, minimum life is 60 sec` when terminating workers quickly. Due to a code issue, we end up trying to reuse the existing worker, stalling the run.
> Fix runner worker reuse issue

- lib/server.js
- tests/behaviour/server.js
Changes console.log line logs from
`[OS X Sierra, Firefox 50.0] {"arguments":["'Random Stuff'"]}`
to
`[OS X Sierra, Firefox 50.0] Random Stuff`
> [Fix] Server output logs for console.log

- bin/cli.js
The issue fixed by this pull request is documented here: https://github.com/browserstack/browserstack-runner/issues/174.
The test terminates while executing `if(worker.launched)` on line #279 in `bin/cli.js`. This occurs because the `worker` variable is undefined. On a study of the variables involved, it seems that this is being caused by a race condition causing `_workers` and `workers` variables to be out of sync, eventually leading to `worker` being undefined.
Changing the condition from `worker.launched` to `!worker || worker.launched` helps avoiding the exception and it was verified that the Travis builds are now working. Here are the builds passing after this change was tried: https://travis-ci.org/reeteshranjan/browse.js/builds/227355846, …
> Fix for Issue #174 (exception seen in Travis)

- lib/_patch/jasmine-jsreporter.js
- lib/_patch/jasmine-plugin.js
- lib/server.js
- tests/external-tests.js
The code that works with `Jasmine` is completely different from the one working with `Mocha` and `QUnit`. The results sent to `_report` api in case of `Jasmine` have very limited information resulting in the case as described in this issue.
It was found that the `Jasmine` reports are as good as `Mocha` ones and it's our code that does not let it pass through in its entirety causing the limited information.
- **jasmine-jsreporter.js** - It has the code that prepares per test suite report, and cuts out detailed information. It was modified to retain detailed information. Also some 'summarization' attributes turned out to be duplicate state post these modifications, and they were removed.
- **jasmine-plugin.js** - It has code that further summarizes the reports created per suite in …
> Fix for Issue #177

- README.md
- bin/cli.js
- bin/runner.js
- lib/server.js
- lib/utils.js
This is a boolean flag in config. If it is set to true, the CLI process with exist with fail if any of the tests failed. This is super convenient in automatic build systems, like Jenkins. Where we normally want to fail the job if any of the tests have failed.
> Add an option of exit with fail on tests fail

- README.md
- bin/cli.js
- bin/runner.js
- lib/config.js
- lib/local.js
- lib/utils.js
* Add support of `config.tunnel_pid` and cli `—pid` param
- It should be a string with a filename to save process id
- It will allow external process to control the tunnel process
- If automated jobs for browserstack hanged or shutdown, we want to kill previous tunnel process manually before starting tests again.
* Add support of `config.test_server_port` param
- If not set, the default 8888 port is used
- List of support ports: https://www.browserstack.com/question/664
> Add `tunnel_pid` and `test_server_port` settings

- lib/_patch/browserstack.js
- tests/behaviour/resources/qunit_test1.js
- tests/behaviour/runner.js
Since upgrading a JS framework (Ember 3.x) we use, Browserstack has failed to run our tests correctly, throwing exceptions and causing test failures.
Internally the framework relies on the presence of `window.console.info` and `window.console.debug` but Browserstack clobbers `window.console` and only re-implements `console.log` and `console.warn`.
This change means we will always have all `window.console` methods, but `console.warn` and `console.log` are still overridden for the runner's purposes.
> Don't clobber window.console

- README.md
- bin/init.js
- bin/runner.js
- package.json
- presets/default.json
- tests/behaviour/runner.js
> Added command line interface using yargs.

- lib/server.js
The logic to match a tag depending on test framework was not consistent when using the test_server configuration option. It would always search for `</head>` and replace that with `</body>` if the framework was not mocha. This PR puts that logic into a function and uses it in both places.
> Use conditional tag matching logic everywhere

- lib/local.js
Currently after installing browserstack-runner you can run one test.
After that, the command is broken. There are numerous symptoms
from this:
* BrowserStackLocal gets re-downloaded every single time.
* an ETXTBSY error appears because the previous file is still busy.
Here is what happens on later runs:
* `fs.exists(localBinary)` finds the binary.
* `runTunnelCmd(['-version'])` gets the following output:
```
$ node_modules/browserstack-runner/lib/BrowserStackLocal -version
Sun Apr 11 2021 20:59:41 GMT+0000 (UTC) -- BrowserStackLocal v8.1
Sun Apr 11 2021 20:59:41 GMT+0000 (UTC) -- Container runtime environment detected
Sun Apr 11 2021 20:59:41 GMT+0000 (UTC) -- Attaching services to public interface
BrowserStack Local version 8.1
```
* Only the first line of data is checked by …
> Fix broken BrowserStackLocal binary after first test
